---
- name: Ensure tmux is installed
  become: true
  community.general.pacman:
    name: tmux
    state: latest

- name: Ensure TPM (tmux plguin manager) is installed
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Install tmux plugins
  ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    creates: ~/.tmux/plugins/nord-tmux
