---
version: '3.8'

services:
  portainer:
    image: portainer/agent
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
    restart: always

  traefik:
    image: traefik
    command:
      - --providers.docker
      - --api.insecure
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  homer:
    image: b4bz/homer
    volumes:
      - ./homer:/www/assets
    labels:
      - traefik.http.routers.homer.rule=Host(`home.lego`)

  gitea:
    image: gitea/gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - /mnt/docker/gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.http.routers.gitea.rule=Host(`git.lego`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000

  gitea_db:
    image: postgres
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db:/var/lib/postgresql/data

  # TODO: Add jellyfin.

volumes:
  # TODO: Should prop move gitea to nas
  gitea:
  gitea_db:
