---
version: '3.8'

services:
  agent:
    image: portainer/agent:{{ portainer_agent_version }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:{{ portainer_version }}
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /mnt/docker/portainer:/data
    networks:
      - agent_network
    labels:
      - traefik.http.routers.portainer.rule=Host(`{{ portainer_domain }}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9443
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-net:
    driver: overlay
    external: true
