# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'archlinux/archlinux'
  config.vm.synced_folder '.', '/vagrant_data', disabled: true
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
    vb.gui = false
  end

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.provision "shell" do |cmd|
    cmd.inline = "sudo pacman -S --noconfirm python"
  end

  config.vm.provision 'ans', type: 'ansible' do |ansible|
    ansible.playbook = 'main.yml'
  end
end
